### ISSUE TITLE
About touch

### ISSUE THREAD

**Issue by lopestom** [crazo7924/android_device_realme_RMX3241#10]
toreton from 4pda write me for know how touch can solve. Here's my answer for him:
It all depends on device model and firmware: Global or other location.
_But if the files (listed below) from the /vendor/firmware folder of both devices are the same and compatible, then add the files in the /vendor/firmware folder:
novatek_ts_fw.bin
novatek_ts_fw_jdi.bin
novatek_ts_fw_tm.bin

Recompile the TWRP. Touch screen test._

**Comment by crazo7924** [comment]
Thanks for the suggestion.

According to the stock kernel config for 8 5G, I see two touch panels — from ilitek and novatek. I don't know if there are more...

Firmwares are available for above two in `/vendor/firmware/tp/`

Adding to this recovery's ramdisk will fix it definitely.

**Comment by crazo7924** [comment]
Didn't work...

**Comment by Dave86a05l** [comment]
Hi everyone. I need help. I would like to install TWRP but I'm using Windows and with adb commands I can't send the phone to fastboot mode. Can you help me?

**Comment by crazo7924** [comment]
> Hi everyone. I need help. I would like to install TWRP but I'm using Windows and with adb commands I can't send the phone to fastboot mode. Can you help me?

Follow my guide:
https://forum.xda-developers.com/t/a-guide-to-unlock-the-bootloader.4306487/

Please read it.

**Comment by Dave86a05l** [comment]
Thanx bru 😁

**Comment by crazo7924** [comment]
Fixed by 9f1e5d56baefcee1068453a0313acf3b3a9f9e5c
