### ISSUE TITLE
Decryption on stock ROM fails

### ISSUE THREAD

**Issue by crazo7924** [crazo7924/android_device_realme_RMX3241#4]

**Comment by EngRudhy** [comment]
Hi Can you please help me to get TWRP for realme 8 

RMX3085

**Comment by crazo7924** [comment]
> Hi Can you please help me to get TWRP for realme 8
> 
> RMX3085

This is a different device. Can't help you with that

**Comment by crazo7924** [comment]
fixed by 9e1494ef678929a9f48f63594ff472ba70266f55
